Update test_docker.yml

diff --git a/.github/workflows/test_docker.yml b/.github/workflows/test_docker.yml
--- a/.github/workflows/test_docker.yml
+++ b/.github/workflows/test_docker.yml
@@ -16,6 +16,7 @@ jobs:
   unit_tests_macos:
     runs-on: macos-11
     steps:
+    
 #       - name: Setup Docker on macOS
 #         uses: douglascamata/setup-docker-macos-action@main
 
@@ -24,26 +25,39 @@ jobs:
         
 #       - name: test docker
 #         run: docker run hello-world 5.2.22
+
     - name: setup docker1
       run: |
-            brew install virtualbox@5.0.12 --cask
-
+            HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+            sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+            open -a /Applications/Docker.app --args --unattended --accept-license
+            echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+            while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
     - name: setup docker2
       run: |
-            brew install docker docker-machine
-            brew services restart docker-machine
+            docker run hello-world
+#     - name: setup docker1
+#       run: |
+#             brew install virtualbox@5.0.12 --cask
+
+#     - name: setup docker2
+#       run: |
+#             brew install docker docker-machine
+#             brew services restart docker-machine
 
             
-    - name: setup docker3
-      run: |
-            sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
-            docker-machine create --driver virtualbox default
+#     - name: setup docker3
+#       run: |
+#             sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
+#             docker-machine create --driver virtualbox default
 
-    - name: setup docker4
-      run: |
+#     - name: setup docker4
+#       run: |
 
-            docker-machine env default
-            eval "$(docker-machine env default)"
-            docker run hello-world
-            docker-machine stop default
+#             docker-machine env default
+#             eval "$(docker-machine env default)"
+#             docker run hello-world
+#             docker-machine stop default
+            
+            
             
